name: apply-to-stg-on-push
on:
  push:
    branches:
      - main
    paths:
      - "environments/stg/**"
      - "*.tf"

jobs:
  apply:
    runs-on: ubuntu-latest
    outputs:
      ecr_registry_url: ${{ steps.tf-apply.outputs.ecr_repository_url }}
      app_url: "http://${{ steps.tf-apply.outputs.app_url }}"

    steps:
      - name: check out repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: TF plan
        id: tf-plan
        run: |
          terraform init -reconfigure -backend-config="environments/stg/backend.config" \
          && terraform plan --var-file="environments/stg/environment.tfvars"

      - name: TF apply
        id: tf-apply
        if: ${{ steps.tf-plan.outcome }} == 'success'
        run: |
          terraform apply -auto-approve --var-file="environments/stg/environment.tfvars"
          echo "ecr_repository_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT
          echo "app_url=$(terraform output -raw app_url)" >> $GITHUB_OUTPUT
